<?php

return [
    'CREATE' => 'USER_CREATE',
    'ACTIVATE' => 'USER_ACTIVATED',
    'STATUS_CHANGE' => 'USER_STATUS_CHANGED',
    'INVITE' => 'INVITE_EMAIL_SENT',
    'ADMIN_ACTIVATION_RESEND' => 'ADMIN_ACTIVATION_RESEND',
    'COURSE_CREATED' => 'COURSE_CREATED',
    'COURSE_DELETED' => 'COURSE_DELETED',
    'COURSE_UPDATED' => 'COURSE_UPDATED',
    'UNIT_CREATED' => 'UNIT_CREATED',
    'UNIT_DELETED' => 'UNIT_DELETED',
    'UNIT_UPDATED' => 'UNIT_UPDATED',
    'LESSON_CREATED' => 'LESSON_CREATED',
    'LESSON_DELETED' => 'LESSON_DELETED',
    'LESSON_UPDATED' => 'LESSON_UPDATED',
    'ACTIVITY_CREATED' => 'ACTIVITY_CREATED',
    'ACTIVITY_UPDATED' => 'ACTIVITY_UPDATED',
    'ACTIVITY_DELETED' => 'ACTIVITY_DELETED',
    'COMPONENT_CREATED' => 'COMPONENT_CREATED',
    'COMPONENT_UPDATED' => 'COMPONENT_UPDATED',
    'COMPONENT_DELETED' => 'COMPONENT_DELETED',

    'LEARNER_CREATED' => 'LEARNER_CREATED',
    'LEARNER_UPDATED' => 'LEARNER_UPDATED',
    'LEARNER_ACTIVATED' => 'LEARNER_ACTIVATED',
    'LEARNER_DEACTIVATED' => 'LEARNER_DEACTIVATED',
    'LEARNER_ACTIVATION_RESEND' => 'LEARNER_ACTIVATION_RESEND',

    'F2F_COMPLETED' => 'F2F_COMPLETED',
    'F2F_UNCOMPLETED' => 'F2F_UNCOMPLETED',
];
